#
# Copyright (C) 2026 tebbi
# SPDX-License-Identifier: GPL-3.0-or-later
#

"""Host network discovery and dnsmasq configuration for the netboot.xyz module."""

import ipaddress
import json
import subprocess

# Interfaces that never carry PXE clients.
_SKIP_PREFIXES = ("lo", "wg", "podman", "cni", "veth", "docker", "br-", "tun", "tap")

# UEFI boot file served to x86_64 / ARM64 UEFI clients, per boot mode. The
# Secure Boot chain uses the Microsoft-signed shim and the iPXE-signed binaries
# the netboot.xyz image downloads from the upstream iPXE release.
UEFI_BOOT_FILES = {
    "standard": {"x86_64": "netboot.xyz.efi", "arm64": "netboot.xyz-arm64.efi"},
    "secureboot": {
        "x86_64": "secureboot-x86_64/shimx64.efi",
        "arm64": "secureboot-arm64/shimaa64.efi",
    },
}
BIOS_BOOT_FILE = "netboot.xyz.kpxe"


def _ip_json(*args):
    out = subprocess.run(["ip", "-j", *args], capture_output=True, text=True, check=True).stdout
    return json.loads(out or "[]")


def list_networks():
    """Return the IPv4 addresses of LAN-facing interfaces.

    Each item: interface, address, prefixlen, network (CIDR), dynamic (DHCP
    lease, may change on reboot).
    """
    networks = []
    for iface in _ip_json("-4", "addr", "show"):
        name = iface.get("ifname", "")
        if name.startswith(_SKIP_PREFIXES):
            continue
        for addr in iface.get("addr_info", []):
            if addr.get("family") != "inet" or addr.get("scope") != "global":
                continue
            net = ipaddress.ip_interface(f"{addr['local']}/{addr['prefixlen']}").network
            networks.append({
                "interface": name,
                "address": addr["local"],
                "prefixlen": addr["prefixlen"],
                "network": str(net),
                "dynamic": bool(addr.get("dynamic", False)),
            })
    return networks


def default_address(networks=None):
    """Pick the address clients should use as boot server.

    Prefer a static address on the interface that carries the default route:
    a DHCP lease can change on reboot and would silently break PXE boot.
    """
    networks = list_networks() if networks is None else networks
    try:
        route = _ip_json("route", "get", "1.1.1.1")[0]
        dev, prefsrc = route.get("dev"), route.get("prefsrc")
    except (subprocess.CalledProcessError, IndexError, ValueError):
        dev, prefsrc = None, None
    candidates = [n for n in networks if n["interface"] == dev] or networks
    for n in candidates:
        if not n["dynamic"]:
            return n
    for n in candidates:
        if n["address"] == prefsrc:
            return n
    return candidates[0] if candidates else None


def find_network(address, networks=None):
    """Return the discovered network entry owning the given address, or None."""
    networks = list_networks() if networks is None else networks
    for n in networks:
        if n["address"] == address:
            return n
    return None


def dnsmasq_conf(proxy_dhcp, server, uefi_mode):
    """Render state/dnsmasq.conf.

    TFTP itself is always enabled by the image's dnsmasq wrapper. With proxyDHCP
    the LAN DHCP server keeps handing out addresses unchanged; dnsmasq only
    answers PXE clients with the boot server and the boot file matching their
    firmware (client architecture, DHCP option 93), so BIOS, UEFI, Secure Boot
    and ARM64 machines all work without touching the router.
    """
    lines = ["# Generated by the netboot.xyz module configure-module action -- do not edit"]
    if not proxy_dhcp or not server:
        lines.append("# proxyDHCP disabled: TFTP only")
        return "\n".join(lines) + "\n"
    net = ipaddress.ip_network(server["network"])
    uefi = UEFI_BOOT_FILES.get(uefi_mode, UEFI_BOOT_FILES["standard"])
    ip = server["address"]
    lines += [
        f"interface={server['interface']}",
        f"dhcp-range={net.network_address},proxy,{net.netmask}",
        # Client firmware (DHCP option 93) and clients that already run iPXE
        # (QEMU/Proxmox VMs, many server NICs), which send user class "iPXE".
        "dhcp-match=set:bios,option:client-arch,0",
        "dhcp-match=set:efi64,option:client-arch,7",
        "dhcp-match=set:efi64,option:client-arch,9",
        "dhcp-match=set:arm64,option:client-arch,11",
        "dhcp-userclass=set:ipxe,iPXE",
        # Classic PXE firmware: one PXE service per architecture, so each client
        # sees exactly one entry and boots it without a menu prompt; the boot
        # file is handed out on the PXE boot server port (4011).
        f'pxe-service=tag:!ipxe,x86PC,"netboot.xyz (BIOS)",{BIOS_BOOT_FILE},{ip}',
        f'pxe-service=tag:!ipxe,BC_EFI,"netboot.xyz (UEFI)",{uefi["x86_64"]},{ip}',
        f'pxe-service=tag:!ipxe,X86-64_EFI,"netboot.xyz (UEFI)",{uefi["x86_64"]},{ip}',
        f'pxe-service=tag:!ipxe,ARM64_EFI,"netboot.xyz (ARM64 UEFI)",{uefi["arm64"]},{ip}',
        # iPXE clients get the boot file directly in the proxyDHCP offer: iPXE
        # drops the broadcast reply of the 4011 boot server exchange, so the PXE
        # menu path never completes for them.
        f"dhcp-boot=tag:ipxe,tag:bios,{BIOS_BOOT_FILE},,{ip}",
        f"dhcp-boot=tag:ipxe,tag:efi64,{uefi['x86_64']},,{ip}",
        f"dhcp-boot=tag:ipxe,tag:arm64,{uefi['arm64']},,{ip}",
    ]
    return "\n".join(lines) + "\n"
