#!/usr/bin/env python3

#
# Copyright (C) 2026 tebbi
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Remove the Traefik route and the firewall service created by configure-module.

import os
import sys
import json

import agent
import agent.tasks

json.load(sys.stdin)
module_id = os.environ["MODULE_ID"]

default_traefik_id = agent.resolve_agent_id("traefik@node")
if default_traefik_id is not None:
    agent.tasks.run(agent_id=default_traefik_id, action="delete-route", data={"instance": module_id})

agent.remove_public_service(module_id)
